### ISSUE TITLE
Simplify: Apply shared properties in CSS to multiple elements at once.

### ISSUE THREAD

**Issue by josephtkim** [FyzxNerd/prj-rev-bwfs-dasmoto#5]
It is usually a good idea to apply shared properties to multiple elements at once, rather than individually to simplify the code. For instance, the font-weight and font-family properties are shared for multiple elements. You can simplify the code like so

```css
h1, h2, .price {
  font-family: Helvetica;
  font-weight: bold;
}
```
